name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'

jobs:
  DeploymenFlow:
    runs-on: ubuntu-latest
    steps:
      - name: print the files in current directory
        run: ls -la