name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'
    comments:
    - '!#NORUN'

jobs:
  DeploymenFlow:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy app to railway
        uses: bervProject/railway-deploy@main
          with:
            railway_token: ${{ secrets.SECRET_RAILWAY_TOKEN }}
            service: "avid-root"

      - name: Send block message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*DipSA 56 CI/CD Submission*\n"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* ${{ vars.NAME }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* ${{ vars.EMAIL }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:* ${{ vars.MAT_NUM }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* \n ${{ github.repositoryUrl }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ vars.RAILWAY_URL }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": false
                    },
                    "value": "click_me_123",
                    "url": " vars.RAILWAY_URL ",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SECRET_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK