name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'

jobs:
  DeploymenFlow:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Deploy app to railway
      #   uses: bervProject/railway-deploy@main
      #   with:
      #     railway_token: ${{}}
      #     service: "my-service"
      #   run: 

      - name: Send block message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*DipSA 56 CI/CD Submission*\n"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* test"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* test"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* test"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* \n test link "
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This is a section block with a button."
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": false
                  },
                  "value": "click_me_123",
                  "url": "https://google.com",
                  "action_id": "button-action"
                }
              }
            ]
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      