name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - '*feature/v*'
    - '!*-*'

jobs:
  DeployAndRun:
  runs-on: ubuntu-latest

  steps:
    - name: test
      run: echo "Pipeline triggered"

  steps: 
    - name: release beta flow
      run: echo "this shoudn't work"