name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'
    comments:
    - '!#NORUN'

jobs:
  DeploymenFlow:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Deploy app to railway
      #   uses: bervProject/railway-deploy@main
      #   env:
      #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
      #   with:
      #     service: "avid-root"

      - name: Send block message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*DipSA 56 CI/CD Submission*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* ${{vars.NAME}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* ${{vars.EMAIL}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:* ${{vars.MATNUM}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n ${{github.repositoryUrl}}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{vars.RAILWAY_URL}}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{vars.RAILWAY_URL}}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PERSONAL_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK