name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'
    comments:
    - '!#NORUN'

jobs:
  DeploymenFlow:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy app to railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "avid-root"
          detach: true

      - name: Send block message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PERSONAL_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK