name: Deploy to Railway and Submit Slack Notification
on:
  push:
    branches:
    - 'release/v*.*'
    - '!*-*'

jobs:
  DeployAndRun:
  runs-on: ubuntu-latest

  steps:
    - name: test
    - run: echo "Pipeline triggered"
